#!/usr/bin/env bash

# Find all boxes which have updates
AVAILABLE_UPDATES=`vagrant box outdated --global | grep outdated | tr -d "*'" | cut -d ' ' -f 2`

for box in $AVAILABLE_UPDATES ; do

  # Find all current versions
  VERSIONS=`vagrant box list | grep $box | cut -d ',' -f 2 | tr -d ' )'`

  # Add latest version
  vagrant box add --clean $box
  BOX_UPDATED="TRUE"

  # Remove all old versions
  for version in $VERSIONS ; do
    vagrant box remove $box -f --box-version=$version
  done

done


if [ ! $BOX_UPDATED ]; then
  echo "All boxes are already up to date!"
else
  echo "All boxes are now up to date!"
fi

vagrant box outdated --global
